- name: app_branches directory check
  tags:
    - apache
  shell: test -d /product/{{ item }} || mkdir -p /product/{{ item }}
  register: app_branches_dir_check
  failed_when: app_branches_dir_check.rc not in [0,1]
  with_items: app_branches

- name: app_branches conf directory check
  tags:
    - apache
  command: test -d /etc/httpd/conf.d/{{ app_name }}/
  register: app_branches_conf_dir_check
  failed_when: app_branches_conf_dir_check.rc not in [0,1]

- name: app_branches conf directory create
  tags:
    - apache
  when: app_branches_conf_dir_check.rc != 0
  file: >
    path=/etc/httpd/conf.d/{{ app_name }}
    state=directory

- name: copy Apache VirtualHost config file
  tags:
    - apache
  template: >
    src=virtualhost.conf.j2
    dest=/etc/httpd/conf.d/virtualhost.conf

- name: copy Apache app app config file
  tags:
    - apache
  template: >
    src=app_branches.conf.j2
    dest=/etc/httpd/conf.d/{{ app_name }}/{{ item }}.conf
  with_items: app_branches

- name: copy Apache app_admin config file
  tags:
    - apache
  template: >
    src=app_admin.conf.j2
    dest=/etc/httpd/conf.d/{{ app_name }}/{{ app_name }}_admin.conf

- name: copy Apache app_media config file
  tags:
    - apache
  template: >
    src=app_media.conf.j2
    dest=/etc/httpd/conf.d/{{ app_name }}/{{ app_name }}_media.conf
