- hosts:
    - localhost
  connection: local
  roles:
    - common/supervisor/fluentd
    - { role: setup/fluentd/app/develop/input/tail, fluentd_tail_configs: "{{ fluentd_app_tail_configs }}", fluentd_filter_grep_configs : "{{ fluentd_develop_filter_grep_configs }}" }
