- hosts:
    - localhost
  connection: local
  vars:
    # Arguments
    Arg__gopath: ""
  roles:
    - role: common/golang/install
      when: "{{ golang__install | bool }} == true"
      golang__gopath: "{{ Arg__gopath | default(golang__gopath, true) }}"
