- hosts:
    - localhost
  connection: local
  vars:
    arg_app_name: test_app
    # Custom Vars
    nginx_root: "/var/www/{{ arg_app_name }}"
    nginx_location_confs:
      - "{{ arg_app_name }}"
    nginx_sendfile: "off"
  roles:
    - role: common/nginx/config/proxy
      nginx_config_proxy_root: "{{ nginx_root }}"
      nginx_config_proxy_config_name: "{{ arg_app_name }}"
      nginx_config_proxy_servers:
      - "{{ arg_app_name }}:9000"
    - common/supervisor/nginx
