- hosts:
    - localhost
  connection: local
  vars:
    arg_app_name: test_app
    arg_admin_name: test_admin
    arg_admin_location: "{{ arg_admin_name }}"
    arg_admin_host: localhost
    # Custom Vars
    nginx_root: "/var/www/{{ arg_app_name }}"
    nginx_location_confs:
      - elasticsearch
      - kibana
      - "{{ arg_admin_name }}"
      - "{{ arg_app_name }}"
  roles:
    #- setup/nginx/backend/golang/revel/develop
    - role: common/nginx/config/proxy
      nginx_config_proxy_root: "{{ nginx_root }}"
      nginx_config_proxy_config_name: "{{ arg_app_name }}"
      nginx_config_proxy_servers:
      - "{{ arg_app_name }}:9000"
    - role: common/nginx/config/rewrite_proxy
      nginx_config_rewrite_proxy_config_name: "{{ arg_admin_name }}"
      nginx_config_rewrite_proxy_location: "/{{ arg_admin_location }}"
      nginx_config_rewrite_proxy_host: "{{ arg_admin_host }}"
      nginx_config_rewrite_proxy_port: 9000
      nginx_config_rewrite_proxy_root: "/var/www/{{ arg_admin_name }}"
    - common/nginx/backend/elasticsearch
    - common/nginx/backend/kibana
    - common/supervisor/nginx
