- hosts:
    - localhost
  connection: local
  vars:
    arg__www_server_name: "www.{{ arg__www_name }}.local"
    arg__app_name: test_app
    # Custom Vars
    nginx_install: false
    nginx_root: "/var/www/{{ arg__app_name }}"
    nginx_sendfile: "off"
    nginx__server_confs:
      - name: ''
        locations:
          - "{{ arg__app_name }}"
  roles:
    - role: common/nginx/config/server
    - role: common/nginx/config/proxy
      nginx_config_proxy__config_name: "{{ arg__app_name }}"
      nginx_config_proxy__root: "{{ nginx_root }}"
      nginx_config_proxy__servers:
      - "{{ arg__app_name }}:9000"
    - role: common/supervisor/nginx
