- hosts:
    - localhost
  connection: local
  roles:
    - common/supervisor/fluentd
    - common/fluentd/config/input/forward
    - { role: setup/fluentd/app/develop/output/elasticsearch, fluentd_elasticsearch_configs: "{{ fluentd_app_elasticsearch_configs }}" }
