- hosts:
    - localhost
  connection: local
  roles:
    - role: common/ruby/install
      when: "{{ ruby__install | bool }} == true"
    - role: common/node/install
      when: "{{ node__install | bool }} == true"
    - role: common/ruby/gem/packages/rails
