nginx_root: "{{ gopath }}/bin/{{ app_name }}/src/{{ revel_package }}/public"
nginx_location_confs:
  - "{{ app_name }}"
nginx_backend_golang_servers:
  - "unix:/{{ gopath }}/bin/{{ app_name }}/socket/{{ app_name }}.sock"
